public class PositionX {
    private String root_pos;
    private String root_role;
    private String root_duty;
    private int vers;
    private int temp;
    private int spor;
    private int prof;
    private int pres;
    private int loy;
    private int injpr;
    private int impm;
    private int dirt;
    private int cont;
    private int cons;
    private int amb;
    private int ada;
    private int cor;
    private int cro;
    private int dri;
    private int fin;
    private int fir;
    private int fre;
    private int head;
    private int lon;
    private int lth;
    private int mar;
    private int pas;
    private int pen;
    private int tck;
    private int tec;
    private int agg;
    private int ant;
    private int bra;
    private int cmp;
    private int dec;
    private int det;
    private int fla;
    private int ldr;
    private int otb;
    private int pos;
    private int tea;
    private int vis;
    private int wor;
    private int acc;
    private int agi;
    private int bal;
    private int jum;
    private int nat;
    private int pac;
    private int sta;
    private int str;
    private int ovo;
    private int aer;
    private int cmd;
    private int com;
    private int cnt;
    private int ecc;
    private int han;
    private int kic;
    private int pun;
    private int ref;
    private int tro;
    private int thr;
    private int height;

    public void PositionX() {

        root_pos = "";
        root_role = "";
        root_duty = "";
        String lft;
        String rft;
        int vers = 0;
        int temp = 0;
        int spor = 0;
        int prof = 0;
        int pres = 0;
        int loy = 0;
        int injpr = 0;
        int impm = 0;
        int dirt = 0;
        int cont = 0;
        int cons = 0;
        int amb = 0;
        int ada = 0;
        int cor = 0;
        int cro = 0;
        int dri = 0;
        int fin = 0;
        int fir = 0;
        int fre = 0;
        int head = 0;
        int lon = 0;
        int lth = 0;
        int mar = 0;
        int pas = 0;
        int pen = 0;
        int tck = 0;
        int tec = 0;
        int agg = 0;
        int ant = 0;
        int bra = 0;
        int cmp = 0;
        int dec = 0;
        int det = 0;
        int fla = 0;
        int ldr = 0;
        int otb = 0;
        int pos = 0;
        int tea = 0;
        int vis = 0;
        int wor = 0;
        int acc = 0;
        int agi = 0;
        int bal = 0;
        int jum = 0;
        int nat = 0;
        int pac = 0;
        int sta = 0;
        int str = 0;
        int ovo = 0;
        int aer = 0;
        int cmd = 0;
        int com = 0;
        int cnt = 0;
        int ecc = 0;
        int han = 0;
        int kic = 0;
        int pun = 0;
        int ref = 0;
        int tro = 0;
        int thr = 0;
        int height = 0;
    }

}
